version: 2
updates:
  - package-ecosystem: npm
    directory: /backend
    schedule:
      interval: weekly
      day: sunday
      time: "06:00"
      timezone: America/New_York
    labels: ["dependencies", "backend"]
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
      include: scope
    groups:
      minor-and-patch-deps:
        update-types: ["minor", "patch"]

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
      day: sunday
      time: "06:30"
      timezone: America/New_York
    labels: ["dependencies", "frontend"]
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
      include: scope
    groups:
      minor-and-patch-deps:
        update-types: ["minor", "patch"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: "07:00"
      timezone: America/New_York
    labels: ["dependencies", "ci"]