blank_issues_enabled: false
contact_links:
  - name: Ask a question or get help
    url: https://github.com/boonker/mbta-commuter-rail-planner/discussions
    about: Please ask and answer questions here.

